stages:
  - build
  - release
  - deploy

variables:
  BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build --pull -t $BRANCH_IMAGE .
    - docker push $BRANCH_IMAGE

release_image:
  stage: release
  only:
    - master
  script:
    - docker pull $BRANCH_IMAGE
    - docker tag $BRANCH_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE

deploy_image:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - echo -n "$id_rsa"
    - eval $(ssh-agent -s) && echo -n "$id_rsa"|ssh-add - 
