version: '2'

services:

  Scrapy:
    image: git.maifusha.com:5005/docker/scrapy:latest
    container_name: scrapy
    hostname: scrapy
    restart: always
    env_file: .env
    volumes:
      - .:/srv/crawl
    links:
      - Mysql

  Mysql:
    image: git.maifusha.com:5005/docker/mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - /srv/mysql/data:/var/lib/mysql
