version: '2'

services:

  Crawler:
    image: 121.40.145.76:4567/docker/scrapy:latest
    container_name: cangweizaixian_spider
    hostname: cangweizaixian_spider
    restart: always
    env_file: .env
    volumes:
      - .:/srv/crawl
    links:
      - Mysql
      - Redis

  Mysql:
    image: 121.40.145.76:4567/docker/mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - /srv/mysql/data:/var/lib/mysql

  Redis:
    image: 121.40.145.76:4567/docker/redis:latest
    container_name: redis
    hostname: redis
    restart: always
    env_file: .env
    ports:
      - '6379:6379'
    volumes:
      - /srv/redis/data:/data
