version: '2'

services:

  StockCrawler:
    image: git.maifusha.com:5005/docker/scrapy:latest
    container_name: stock_crawler
    hostname: stock_crawler
    restart: always
    env_file: .env
    volumes:
      - .:/srv/crawl
    links:
      - Mysql
      - Redis

  Mysql:
    image: git.maifusha.com:5005/docker/mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - /srv/mysql/data:/var/lib/mysql

  Redis:
    image: git.maifusha.com:5005/docker/redis:latest
    container_name: redis
    hostname: redis
    restart: always
    env_file: .env
    ports:
      - '6379:6379'
    volumes:
      - /srv/redis/data:/data
